version: '3'
services:
  backend:
    build:
      context: ./to-do-application-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./to-do-application-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
